export const EVENT_LISTENER_KEY = "EVENT-LISTENER-";

export const CATEGORIES_STORAGE_KEY = "CATEGORIES";
export const SHOP_LIST_KEY = "SHOP-LIST-KEY";

export const storeKeysList = [CATEGORIES_STORAGE_KEY, SHOP_LIST_KEY];
